use crate::material::{AMBIENT_TEMP, Material};
use Material::*;

mod atmosphere;
mod core;
mod effects;
mod heat;
mod movement;
mod reactions;
mod scenes;
mod structural;

pub use core::{Scene, World};

// Types used by sibling modules.
/// Simple deterministic 64-bit xorshift* PRNG used by the simulation.
/// Generates deterministic values from a seedable state.
#[derive(Clone)]
pub(crate) struct Prng {
    state: u64,
}

impl Prng {
    pub fn new(seed: u64) -> Self {
        // Avoid the all-zero state (xorshift* would lock up).
        Self {
            state: if seed == 0 { 1 } else { seed },
        }
    }

    pub fn next_u64(&mut self) -> u64 {
        let mut x = self.state;
        x ^= x >> 12;
        x ^= x << 25;
        x ^= x >> 27;
        self.state = x;
        x.wrapping_mul(0x2545_F491_4F6C_CD1D)
    }

    pub fn next_u8(&mut self) -> u8 {
        self.next_u64() as u8
    }

    pub fn gen_range(&mut self, min: u16, max: u16) -> u16 {
        let range = (max - min + 1) as u64;
        min + (self.next_u64() % range) as u16
    }
}

const FIRE_LIFE_MIN: u16 = 60;
const FIRE_LIFE_MAX: u16 = 100;
const EMBER_LIFE_MIN: u16 = 80;
const EMBER_LIFE_MAX: u16 = 170;
const STEAM_LIFE_MIN: u16 = 120;
const STEAM_LIFE_MAX: u16 = 280;
const SMOKE_LIFE_MIN: u16 = 80;
const SMOKE_LIFE_MAX: u16 = 180;
const GUNPOWDER_BLAST_RADIUS: i32 = 5;
const TNT_BLAST_RADIUS: i32 = 10;
const C4_BLAST_RADIUS: i32 = 12;

/// Instantaneous blast parameters. Duration comes from lingering atmospheric
/// overpressure rather than a multi-tick scripted wave.
#[derive(Clone, Copy)]
pub(crate) struct BlastProfile {
    pub radius: i32,
    /// Peak air-mass injection scale (ambient units at the epicentre).
    pub pressure: i32,
    /// Peak heat pulse in °C at the epicentre.
    pub heat: i16,
    /// Peak structural damage at the epicentre.
    pub damage: u8,
    /// Peak outward impulse in quarter-cell velocity units.
    pub impulse: i8,
}

const GUNPOWDER_BLAST: BlastProfile = BlastProfile {
    radius: GUNPOWDER_BLAST_RADIUS,
    pressure: 2,
    heat: 180,
    // Floor strength 350 keeps soft solids breakable out to the radius edge.
    damage: 48,
    // Quarter-cell units; peak ~2-3 whole cells/tick after scale.
    impulse: 10,
};
const TNT_BLAST: BlastProfile = BlastProfile {
    radius: TNT_BLAST_RADIUS,
    pressure: 3,
    heat: 320,
    damage: 52,
    impulse: 12,
};
const C4_BLAST: BlastProfile = BlastProfile {
    radius: C4_BLAST_RADIUS,
    pressure: 4,
    heat: 260,
    // High enough to shatter stone/glass across the radius; metal/concrete soak.
    damage: 52,
    impulse: 14,
};
/// Ticks a fuse cell smoulders before flaring to fire and kindling its
/// neighbours. Sets the burn-front pace: one cell advances per this many ticks.
pub(crate) const FUSE_BURN_TICKS: u16 = 3;

const CHUNK_W: usize = 64;
const CHUNK_H: usize = 32;
const MAX_VELOCITY: i8 = 4;
const VELOCITY_SCALE: i8 = 4;
const GRAVITY_PER_TICK: i8 = 1;

pub(crate) const ATMOS_SCALE: i16 = 64;
/// Ambient dry air mass per cell (fixed-point).
pub(crate) const AMBIENT_AIR_MASS: i16 = ATMOS_SCALE;
/// Maximum air mass per cell (clamped to prevent runaway pressure).
pub(crate) const MAX_AIR_MASS: i16 = ATMOS_SCALE * 4;
/// Ambient oxygen fraction of air mass (21%).
pub(crate) const AMBIENT_O2: i16 = (AMBIENT_AIR_MASS as i32 * 21 / 100) as i16;
/// Maximum transport per direction per tick.
pub(crate) const MAX_TRANSPORT: i16 = 8;
/// Pressure impulse strength scale.
pub(crate) const PRESSURE_SCALE: i32 = 8;
/// Effective unseen depth represented by each 2D cell during combustion.
const COMBUSTION_DEPTH: u64 = 8;
/// Base flames consume one oxygen unit at this interval (2 / depth per tick).
const FIRE_OXYGEN_INTERVAL: u64 = COMBUSTION_DEPTH / 2;
/// Decorative flames without adjacent fuel consume oxygen more slowly.
const FREE_FLAME_OXYGEN_INTERVAL: u64 = COMBUSTION_DEPTH;
/// Extra life lost per critically starved tick, giving a 20–40 tick fade-out.
const CRITICAL_FIRE_LIFE_LOSS: u16 = 2;
/// Oxygen concentration percentages used to stage combustion.
const CRITICAL_OXYGEN_PERCENT: i32 = 5;
const LOW_OXYGEN_PERCENT: i32 = 12;

/// Fraction of cooled embers that leave a residue of ash; the rest are fully
/// consumed by the burn.
const ASH_CHANCE_PER_MILLE: u32 = 50;

/// Maximum horizontal velocity generated by hydrostatic head. This doubles as
/// a coarse viscosity model: runny liquids turn pressure into faster jets while
/// gels and molten rock dissipate it locally.
fn pressure_speed_of(m: Material) -> i8 {
    match m {
        Water | LiquidNitrogen | Mercury => 4,
        Acid => 3,
        Oil => 2,
        Napalm | Lava => 1,
        _ => 0,
    }
}

fn chunks_x(width: usize) -> usize {
    width.div_ceil(CHUNK_W)
}

fn chunks_y(height: usize) -> usize {
    height.div_ceil(CHUNK_H)
}

fn chunks_len(width: usize, height: usize) -> usize {
    chunks_x(width) * chunks_y(height)
}

fn activate_chunk_neighborhood(
    width: usize,
    height: usize,
    chunks_x: usize,
    x: usize,
    y: usize,
    chunks: &mut [bool],
) {
    if width == 0 || height == 0 || chunks_x == 0 || chunks.is_empty() {
        return;
    }

    let x0 = x.saturating_sub(1) / CHUNK_W;
    let y0 = y.saturating_sub(1) / CHUNK_H;
    let x1 = (x + 1).min(width - 1) / CHUNK_W;
    let y1 = (y + 1).min(height - 1) / CHUNK_H;

    for cy in y0..=y1 {
        for cx in x0..=x1 {
            if let Some(chunk) = chunks.get_mut(cy * chunks_x + cx) {
                *chunk = true;
            }
        }
    }
}

impl World {
    pub(crate) fn rand_life(&mut self, m: Material) -> u16 {
        match m {
            Fire => self.rand_range(FIRE_LIFE_MIN, FIRE_LIFE_MAX),
            Ember => self.rand_range(EMBER_LIFE_MIN, EMBER_LIFE_MAX),
            Steam => self.rand_range(STEAM_LIFE_MIN, STEAM_LIFE_MAX),
            Smoke => self.rand_range(SMOKE_LIFE_MIN, SMOKE_LIFE_MAX),
            _ => 0,
        }
    }

    pub(crate) fn rand_range(&mut self, min: u16, max: u16) -> u16 {
        self.prng.gen_range(min, max)
    }

    /// Generate a random life via `rand_range` then call `put`.  Splitting the
    /// borrow across two statements avoids E0499 nested-mutable-borrow errors.
    pub(crate) fn put_rand_range(&mut self, i: usize, m: Material, min: u16, max: u16) {
        let life = self.rand_range(min, max);
        self.put(i, m, life);
    }
}
