use rand::Rng;

use crate::material::{AMBIENT_TEMP, Material};
use Material::*;

mod atmosphere;
mod core;
mod effects;
mod heat;
mod reactions;
mod scenes;

pub use core::{Scene, World};

const FIRE_LIFE_MIN: u16 = 60;
const FIRE_LIFE_MAX: u16 = 100;
const EMBER_LIFE_MIN: u16 = 80;
const EMBER_LIFE_MAX: u16 = 170;
const STEAM_LIFE_MIN: u16 = 120;
const STEAM_LIFE_MAX: u16 = 280;
const SMOKE_LIFE_MIN: u16 = 80;
const SMOKE_LIFE_MAX: u16 = 180;
const GUNPOWDER_BLAST_RADIUS: i32 = 5;
const TNT_BLAST_RADIUS: i32 = 10;
const C4_BLAST_RADIUS: i32 = 12;
/// Ticks a fuse cell smoulders before flaring to fire and kindling its
/// neighbours. Sets the burn-front pace: one cell advances per this many ticks.
pub(crate) const FUSE_BURN_TICKS: u16 = 3;

const CHUNK_W: usize = 64;
const CHUNK_H: usize = 32;
const MAX_VELOCITY: i8 = 4;
const VELOCITY_SCALE: i8 = 4;
const GRAVITY_PER_TICK: i8 = 1;

pub(crate) const ATMOS_SCALE: i16 = 64;
/// Ambient dry air mass per cell (fixed-point).
pub(crate) const AMBIENT_AIR_MASS: i16 = ATMOS_SCALE;
/// Maximum air mass per cell (clamped to prevent runaway pressure).
pub(crate) const MAX_AIR_MASS: i16 = ATMOS_SCALE * 4;
/// Ambient oxygen fraction of air mass (21%).
pub(crate) const AMBIENT_O2: i16 = (AMBIENT_AIR_MASS as i32 * 21 / 100) as i16;
/// Maximum transport per direction per tick.
pub(crate) const MAX_TRANSPORT: i16 = 8;
/// Pressure impulse strength scale.
pub(crate) const PRESSURE_SCALE: i32 = 8;

/// Fraction of cooled embers that leave a residue of ash; the rest are fully
/// consumed by the burn.
const ASH_CHANCE_PER_MILLE: u32 = 50;

/// How far a liquid tries to flow sideways in one tick. Bigger = flatter water;
/// lava stays viscous.
fn spread_of(m: Material) -> usize {
    match m {
        Water | LiquidNitrogen => 6,
        Mercury => 5,
        Acid | Oil => 4,
        _ => 1,
    }
}

/// Maximum horizontal velocity generated by hydrostatic head. This doubles as
/// a coarse viscosity model: runny liquids turn pressure into faster jets while
/// gels and molten rock dissipate it locally.
fn pressure_speed_of(m: Material) -> i8 {
    match m {
        Water | LiquidNitrogen | Mercury => 4,
        Acid => 3,
        Oil => 2,
        Napalm | Lava => 1,
        _ => 0,
    }
}

/// Momentum retained after ordinary surface flow.
fn flow_momentum_of(m: Material) -> i8 {
    match m {
        Water | LiquidNitrogen | Mercury => 2,
        Acid | Oil => 1,
        _ => 0,
    }
}

fn chunks_x(width: usize) -> usize {
    width.div_ceil(CHUNK_W)
}

fn chunks_y(height: usize) -> usize {
    height.div_ceil(CHUNK_H)
}

fn chunks_len(width: usize, height: usize) -> usize {
    chunks_x(width) * chunks_y(height)
}

fn activate_chunk_neighborhood(
    width: usize,
    height: usize,
    chunks_x: usize,
    x: usize,
    y: usize,
    chunks: &mut [bool],
) {
    if width == 0 || height == 0 || chunks_x == 0 || chunks.is_empty() {
        return;
    }

    let x0 = x.saturating_sub(1) / CHUNK_W;
    let y0 = y.saturating_sub(1) / CHUNK_H;
    let x1 = (x + 1).min(width - 1) / CHUNK_W;
    let y1 = (y + 1).min(height - 1) / CHUNK_H;

    for cy in y0..=y1 {
        for cx in x0..=x1 {
            if let Some(chunk) = chunks.get_mut(cy * chunks_x + cx) {
                *chunk = true;
            }
        }
    }
}

fn rand_life(m: Material) -> u16 {
    match m {
        Fire => rand_range(FIRE_LIFE_MIN, FIRE_LIFE_MAX),
        Ember => rand_range(EMBER_LIFE_MIN, EMBER_LIFE_MAX),
        Steam => rand_range(STEAM_LIFE_MIN, STEAM_LIFE_MAX),
        Smoke => rand_range(SMOKE_LIFE_MIN, SMOKE_LIFE_MAX),
        _ => 0,
    }
}

fn rand_range(min: u16, max: u16) -> u16 {
    rand::thread_rng().gen_range(min..=max)
}
